### PR TITLE
Changing code per Mark's request.

### PR DESCRIPTION
**Pull request by bdenison99**
This should hopefully complete the >2TB target fixes

### CODE REVIEW

**Comment by bdenison99** [comment]
Hope this helps.

**Comment by lauracaulfield** [comment]
I can't find the changes to pull into the master branch, and they're not in the master branch now.  I think you have to reopen the pull request so the magical button appears.

**Comment by bdenison99** [comment]
Re-opened

**Comment by lauracaulfield** [comment]
perfect, thanks Bart!

**Pull request merged**
