### PR TITLE
Fixing integer overflow when target >2TB

### PR DESCRIPTION
**Pull request by bdenison99**

### CODE REVIEW

**Comment by bdenison99** [comment]
This is some additional changes that I hope will fix the GLE:87 errors which map to invalid parameters.  These all seem to stem from >2TB disk sizes.  Most of the fixes were to change int to int64_t, and stoi to _atoi64.  I've tested the latest failing test iterations with this new code, and it worked instead of crashing.  Hoping not to see any more.

**Comment by marksantaniello** [comment]
I'd prefer stoll over _atoi64/c_str.
http://www.cplusplus.com/reference/string/stoll/

**Comment by bdenison99** [comment]
Any particular reason/benefit for using stoll over _atoi64?

**Comment by marksantaniello** [comment]
It's just the modern C++ standards-compliant way to accomplish the same thing.  Avoids the pointless c_str() business too.

**Comment by bdenison99** [comment]
OK - created a new pull request with the _atoi64 converted to std::stoll.  Here's hoping that's the end of the >2TB issues.

**Comment by marksantaniello** [comment]
Thanks very much for the fix!

**Pull request closed without merging**
